### ISSUE TITLE
MDB2_Error::fetchRow error

### ISSUE THREAD

**Issue by trippleflux** [technion/maia_mailguard#19]
I have got the following when logging in :

2015/01/13 14:43:35 [error] 66901#0: *104 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method MDB2_Error::fetchRow() in /local/www/mail/php/auth.php on line 323" while reading response header from upstream, client: 10.8.8.8, server: mail.example.com, request: "POST /php/xlogin.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "mail.example.com", referrer: "https://mail.example.com/php/login.php"

**Comment by technion** [comment]
What authentication method have you configured?

Have you run through the configtest.php and assured that everything checks out?

The difficulty here is that the legacy was that no SQL was ever error checked, so thousands of these errors showed up on a modern OS and I spent a lot of time inserting error checking to deal with it. The fact you seem to have hit an error without such a check suggests you've also managed to hit an untested code path.

**Comment by trippleflux** [comment]
I am using postfix 2.11.3 + dovecot 2.2.15 sql auth method on freebsd 10.1, yup i have run configtest.php, all passed, although there is bug for check write permission on theme dir, i need to manually creating the compiled dir on each of theme folder and set 777 as permission.

On related 1.0.3 i have encountered login page loop bugs http://www.renaissoft.com/cgi-bin/mailman/private/maia-users/2015-January/016388.html .

**Comment by technion** [comment]
>What authentication method have you configured?

Please answer the above question.

>On related 1.0.3 i have encountered login page loop bugs

If you are getting an SQL error in the authentication module I would highly suspect it's related.

**Comment by technion** [comment]
Please try the current commit. I suspect we have identified an SQL auth user, and I've just implemented the proper patterns for this.

**Comment by trippleflux** [comment]
Authentication method is sql with postfix database, table name mailbox, e-mail column username. Will do trying current commit when Janky Jay posting new freebsd port for maia and the guide :+1: .

**Comment by trippleflux** [comment]
In addition, this issues also appears when enabling graph for stats 
2015/01/20 18:52:09 [error] 46372#0: *806 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method MDB2_Error::fetchrow() in /local/www/maia/stats.php on line 117" while reading response header from upstream, client: 10.8.8.8, server: mail.example.com, request: "GET /stats.php?Maia104=fm100qu21qcu9h2u9blh9b5ci7& HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "mail.luminousify.com", referrer: "https://mail.example.com/welcome.php?Maia104=fm100qu21qcu9h2u9blh9b5ci7&"

**Comment by technion** [comment]
There is definitely an issue identified with cookies or session storage on your server, that doesn't appear to exist elsewhere. Once we get that sorted I suspect we'll fix a number of things, so I'll hold off investigating that issue until we do.

**Comment by trippleflux** [comment]
@technion the session issue now fixed. The error above still appear.

**Comment by technion** [comment]
Thanks for this confirmation. With the session issue resolved, this error is something I can work with. I'll jump onto your test server throughout the long weekend and work on this if it's OK.

**Comment by trippleflux** [comment]
Sure go ahead, would love if you can make sql auth method working.

**Comment by trippleflux** [comment]
If possible sql auth with SHA512-CRYPT method supported, by using doveadm pw apps.

**Comment by technion** [comment]
Hi,

Please grab the latest update (only change is stats.php) and advise if issue persists.

**Comment by trippleflux** [comment]
@technion the stats.php confirmed fixed but auth.php still problems.

**Comment by technion** [comment]
Can you show me the auth error you are having?

**Comment by trippleflux** [comment]
The one on the top of the this issue : 
2015/01/13 14:43:35 [error] 66901#0: *104 FastCGI sent in stderr: "PHP message: PHP Fatal error: Call to undefined method MDB2_Error::fetchRow() in /local/www/mail/php/auth.php on line 323" while reading response header from upstream, client: 10.8.8.8, server: mail.example.com, request: "POST /php/xlogin.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "mail.example.com", referrer: "https://mail.example.com/php/login.php" .

Only happens if the auth method is sql into postfix database.

**Comment by technion** [comment]
> FastCGI 

That message should never happen when running mod_php, like we moved to earlier?

**Comment by technion** [comment]
Actually, regardless of that, I think I can see it. Can you please delete like 322? I'm not near enough computing power to test that out until tomorrow.

**Comment by trippleflux** [comment]
Removing line 322 still causing error :
[Tue Jan 27 15:52:36.370928 2015] [:error] [pid 5047:tid 36859639808] [client 10.8.8.8:52871] PHP Fatal error:  Call to a member function fetchRow() on null in /local/www/maia/auth.php on line 323, referer: https://mail.example.com/login.php

**Comment by trippleflux** [comment]
@technion 
After adding like what you have done into stats.php, i have some progress on php problems finding mdb2 mysql driver : MDB2 Error: not found, [Error message: Unable to bind to missing placeholder: 0], i have checked my include_path and it's correct, any idea why the code couldn't found mdb2 mysql driver while configtest.php mentioned it's installed ?.

My include_path : include_path = ".:/usr/local/share/pear:/usr/local/share/smarty"

**Comment by technion** [comment]
The pattern from stats.php was not followed in the above code, and that's an invalid prepare() call. I've fixed this in your server and committed a fix.
