### ISSUE TITLE
Login pages loop

### ISSUE THREAD

**Issue by trippleflux** [technion/maia_mailguard#20]
I am using the current commit, my authentication method is pop3, on dovecot i can see i have logged in, but in maia web interface i am going return back to login page, on maia database i can see my account is super administrator. What will the cause of this?

**Comment by technion** [comment]
You said on issue #19  that you were using SQL authentication. 

I'm struggling to understand what you're doing that's triggering these issues. They have no occurred on any other deployment I've seen. Since you appear to have a different environment, I'll go back to the start - can you confirm configtest.php produces no errors, and then check your Apache logs for any errors or output?

**Comment by trippleflux** [comment]
I am also baffle as this is the third install on my box to make sure i am not doing anything wrong, configtest.php all shown green, i am using nginx, in my logs there is nothing logged.

**Comment by trippleflux** [comment]
If you need root access to the mail box, i can grant you one, give me your e-mail, i will send you one.

**Comment by technion** [comment]
Assuming this is currently a nonproduction server, feel free to send some credentials to technion@lolware.net and I will take a look at it. I would also require a valid logon to the maia interface. I'd be interested in sorting this out once and for all.

**Comment by trippleflux** [comment]
I have rechecked all of the config line by line and couldn't figure it out which i have done it wrong, btw the credentials has been sent.

**Comment by technion** [comment]
As per direct communication, I highly suspect this is due to the absolute pathnames vs the subfolder installed in. Long term I will fix this, short term, I would recommend a subdomain pointing right at the root.

**Comment by trippleflux** [comment]
I have put in root now, now the images and css loaded (from chrome) but still getting login loop.

**Comment by technion** [comment]
Thanks for this update - I'll jump back on the server in question now.

**Comment by trippleflux** [comment]
This issue has been fixed by joshua & technion, i couldn't send much grateful to them for fixing this, the fix lies in php.ini config session.use_only_cookies = 0, make sure it's 0.

**Comment by trippleflux** [comment]
The issues seems still persist unless i am clearing out the cookies each time i am logging in.

**Comment by technion** [comment]
I did not realise you disabled cookies altogether - let's get  used_cookies turned back on so we can continue working on this as a "normal" server.

**Comment by trippleflux** [comment]
Fixed by setting 
session.save_path = "/tmp"
session.auto_start = 1
in php.ini

**Comment by technion** [comment]
As per email, I believe we've found something about your server really doesn't like mixed case session names. I have renamed to MAIA104 and it seems to work. Can you confirm?

I still don't know if this is your version of PHP, an FBSD thing, a security setting somewhere or what, but I will commit to mainline if this corrects it.

**Comment by trippleflux** [comment]
It's quite correct fix but if a user forgot to logged out, then the issue will persist.

**Comment by trippleflux** [comment]
The issues fixed with apache 2.4, mod_php, php 5.6, somehow there is a problem with session on php-fpm and maia.

**Comment by technion** [comment]
Great, thanks for that confirmation.

**Comment by joh-ku** [comment]
Hi Folks,
i currently run into the very same issue as described here. However, the strange thing is that i only have that issue when i access my webserver externally via domain name. When i load maia from within my internal network by the servers ip-address, i can log in successfully. The maia/postfix/dovecot log as well as the HTTPd log do not throw any specific errors. I only see the following error message in httpd-error.log (but for both internal and external access - so i don't think this is related to the issue):

```
[Mon Apr 06 20:41:50.862570 2020] [php7:warn] [pid 3490] [client 192.168.178.22:46940] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/share/pear/MDB2.php on line 826, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.880900 2020] [php7:warn] [pid 3490] [client 192.168.178.22:46940] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/share/pear/MDB2.php on line 826, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.886171 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.891908 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.892235 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.892536 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.892778 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.893271 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.893568 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.893982 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.894339 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.894880 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.895232 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.895498 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.896007 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.896314 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.896781 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.897053 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.897277 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
[Mon Apr 06 20:41:50.897454 2020] [php7:notice] [pid 3490] [client 192.168.178.22:46940] PHP Notice:  A non well formed numeric value encountered in /usr/local/share/pear/MDB2/Driver/mysqli.php on line 1154, referer: http://192.168.178.115/maia/login.php?prevlang=en
``` 

Can anyone push me in the right direction? Any hints on what to look at next?

```
*SYSTEM INFORMATION*
OS: FreeBSD 12.1-RELEASE-p3 GENERIC
Apache: Apache/2.4.43
PHP: PHP 7.2.29 (cli) (built: Mar 24 2020 13:12:36) ( NTS )
Maia Mailguard: 1.0.4
Postfix: 3.5.0
Dovecot: 2.3.10 (0da0eff44)
```

**Comment by styelz** [comment]
You can try incogneto mode or clear your browser cache instead.. i think..

**Comment by joh-ku** [comment]
Hi @styelz - thank you for this input. Unfortunately, deleting the browser cache or starting it in incognito mode does not fix the issue.

However, this morning I figured out the root cause of my problem - it's my reverse proxy. I'm running maia mailguard behind an apache proxy server. When i forward requests from my router to maia directly, the login loop issue disappears immediately. I now have to find the missing piece to get this working through my reverse proxy...
